// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: openliberty-operator-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-02-28
:page-description: Explore how to deploy a microservice to Kubernetes by using Open Liberty Operator.
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'cloud-openshift-operator', 'okd']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Deploying a microservice to Kubernetes by using Open Liberty Operator
:page-seo-description: A getting started tutorial with examples on how to deploy a cloud-native Java application and a microservice to a Kubernetes cluster by using a Kubernetes Operator like the Open Liberty Operator.
:guide-author: Open Liberty
= Deploying a microservice to Kubernetes by using Open Liberty Operator

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy a microservice to Kubernetes by using Open Liberty Operator.

:kube: Kubernetes

== What you'll learn

You will learn how to deploy a cloud-native application with a microservice to Kubernetes by using the Open Liberty Operator. 

https://www.kubernetes.io/[Kubernetes^] is a container orchestration system. It streamlines the DevOps process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the deployment and management of cloud applications easier. You can learn more about Kubernetes by checking out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^] guide.

https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#operators-in-kubernetes[Kubernetes operators^] provide an easy way to automate the management and updating of applications by abstracting away some of the details of cloud application management. To learn more about operators, check out this https://www.openshift.com/learn/topics/operators[Operators tech topic article^]. 

The application in this guide consists of one microservice, `system`. The system microservice returns the JVM system properties of its host.

You will deploy the `system` microservice by using the Open Liberty Operator. The https://github.com/OpenLiberty/open-liberty-operator[Open Liberty Operator^] provides a method of packaging, deploying, and managing Open Liberty applications on Kubernetes-based clusters. The Open Liberty Operator watches Open Liberty resources and creates various Kubernetes resources, including `Deployments`, `Services`, and `Routes`, depending on the configurations. The Operator then continuously compares the current state of the resources, the desired state of application deployment, and reconciles them when necessary.


// Static guide instruction
ifndef::cloud-hosted[]
[role='command']
include::{common-includes}/kube-prereq.adoc[]
endif::[]

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Starting and preparing your cluster for deployment
// =================================================================================================
// Static guide instruction
ifndef::cloud-hosted[]
[role='command']
include::{common-includes}/kube-start.adoc[]
endif::[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

== Installing the Operator

// Static guide instruction
ifndef::cloud-hosted[]
Before you can deploy your microservice, you must install the Open Liberty Operator. You should read the official installation document on the link:https://github.com/OpenLiberty/open-liberty-operator/blob/main/deploy/releases/0.7.1/readme.adoc[GitHub repository].

First, install Custom Resource Definitions (CRDs) for the Open Liberty Operator by running the following command:
[role='command']
```
kubectl apply -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.1/openliberty-app-crd.yaml
```
Custom Resources extend the Kubernetes API and enhance its functionality.

Set environment variables for namespaces for the Operator by running the following commands:
[role='command']
```
OPERATOR_NAMESPACE=default
WATCH_NAMESPACE='""'
```

Next, run the following command to install cluster-level role-based access:
[role='command']
```
curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/main/deploy/releases/0.7.1/openliberty-app-cluster-rbac.yaml \
  | sed -e "s/OPEN_LIBERTY_OPERATOR_NAMESPACE/${OPERATOR_NAMESPACE}/" \
  | kubectl apply -f -
```

Finally, run the following command to install the Operator:
[role='command']
```
curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/main/deploy/releases/0.7.1/openliberty-app-operator.yaml \
  | sed -e "s/OPEN_LIBERTY_WATCH_NAMESPACE/${WATCH_NAMESPACE}/" \
  | kubectl apply -n ${OPERATOR_NAMESPACE} -f -
```
endif::[]

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
In this Skills Network environment, the Open Liberty Operator is already installed by the administrator. If you like to learn how to install the Open Liberty Operator, you can learn from the [Deploying microservices to OpenShift by using Kubernetes Operators](https://openliberty.io/guides/cloud-openshift-operator.html#installing-the-operators) guide or the Open Liberty Operator [document](https://github.com/OpenLiberty/open-liberty-operator/blob/master/deploy/releases/0.7.1/readme.adoc).
endif::[]

[role='command']
include::{common-includes}/cloud-hosted/skills-network-kube-setup.adoc[]

To check that the Open Liberty Operator has been installed successfully, run the following command to view all the supported API resources that are available through the Open Liberty Operator:
[role='command']
```
kubectl api-resources --api-group=openliberty.io
```

Look for the following output, which shows the https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource definitions^] (CRDs) that can be used by the Open Liberty Operator:

[role='no_copy']
```
NAME                      SHORTNAMES         APIGROUP         NAMESPACED   KIND
openlibertyapplications   olapp,olapps       openliberty.io   true         OpenLibertyApplication
openlibertydumps          oldump,oldumps     openliberty.io   true         OpenLibertyDump
openlibertytraces         oltrace,oltraces   openliberty.io   true         OpenLibertyTrace
```

Each CRD defines a kind of object that can be used, which is specified in the previous example by the `KIND` value. The `SHORTNAME` value specifies alternative names that you can substitute in the configuration to refer to an object kind. For example, you can refer to the `OpenLibertyApplication` object kind by one of its specified shortnames, such as `olapps`. 

The `openlibertyapplications` CRD defines a set of configurations for deploying an Open Liberty-based application, including the application image, number of instances, and storage settings. The Open Liberty Operator watches for changes to instances of the `OpenLibertyApplication` object kind and creates Kubernetes resources that are based on the configuration that is defined in the CRD.

== Deploying the system microservice to Kubernetes

To deploy the `system` microservice, you must first package the microservice, then create and build a runnable container image of the packaged microservice.

=== Packaging the microservice

Ensure that you are in the `start` directory and run the following command to package the `system` microservice:

// Static guide instruction
ifndef::cloud-hosted[]
[role='command']
```
mvn clean package
```
endif::[]

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
```
cd /home/project/draft-guide-openliberty-operator-intro/start
mvn clean package
```
{: codeblock}
endif::[]

=== Building the image

include::{common-includes}/ol-icr-full-docker-pull.adoc[]

Next, run the `docker build` command to build the container image for your application:
[role='command']
```
docker build -t system:1.0-SNAPSHOT system/.
```

The `-t` flag in the `docker build` command allows the Docker image to be labeled (tagged) in the `name[:tag]` format. The tag for an image describes the specific image version. If the optional `[:tag]` tag is not specified, the `latest` tag is created by default.

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
Next, push your images to the container registry on IBM Cloud with the following commands:

```
docker tag system:1.0-SNAPSHOT us.icr.io/$NAMESPACE_NAME/system:1.0-SNAPSHOT
docker push us.icr.io/$NAMESPACE_NAME/system:1.0-SNAPSHOT
```
{: codeblock}
endif::[]

Now you're ready to deploy the image.

=== Deploying the image
//File 0
deploy.yaml
[source, yaml, linenums, role='code_column hide_tags=healthProbes']
----
include::finish/deploy.yaml[]
----

You can configure the specifics of the Open Liberty Operator-controlled deployment with a YAML configuration file.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `deploy.yaml` configuration file in the `start` directory.#
`deploy.yaml`
----

The [hotspot file=0]`deploy.yaml` file is configured to deploy one [hotspot=olapp file=0]`OpenLibertyApplication` resource, [hotspot=system file=0]`system`, which is controlled by the Open Liberty Operator.

The [hotspot=sysImage file=0]`applicationImage` parameter defines what container image is deployed as part of the `OpenLibertyApplication` CRD. 
ifndef::cloud-hosted[]
This parameter follows the `<image-name>[:tag]` format. The parameter can also point to an image hosted on an external registry, such as Docker Hub. 
endif::[]
ifdef::cloud-hosted[]
This parameter follows the **[image-name][:tag]** format. The parameter can also point to an image hosted on an external registry, such as Docker Hub. 
endif::[]
The `system` microservice is configured to use the [hotspot=sysImage file=0]`image` created from the earlier build. 

The [hotspot=systemEnv file=0]`env` parameter is used to specify environment variables that are passed to the container at runtime.

Additionally, the microservice includes the [hotspot=service file=0]`service` and [hotspot=expose file=0]`expose` parameters. The [hotspot=servicePort file=0]`service.port` parameter specifies which port is exposed by the container, allowing the microservice to be accessed from outside the container. To access the microservice from outside of the cluster, it must be exposed by setting the [hotspot=expose file=0]`expose` parameter to `true`. After you expose the microservice, the Operator automatically creates and configures routes for external access to your microservice.

// Static guide instruction
ifndef::cloud-hosted[]
Run the following command to deploy the `system` microservice with the previously explained configuration:

[role='command']
```
kubectl apply -f deploy.yaml
```
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Run the following commands to update the **applicationImage** and deploy the **system** microservice with the previously explained configuration:
```
sed -i 's=system:1.0-SNAPSHOT=us.icr.io/'"$NAMESPACE_NAME"'/system:1.0-SNAPSHOT\n  imagePullPolicy: Always=g' deploy.yaml
kubectl apply -f deploy.yaml
```
{: codeblock}
endif::[]

Next, run the following command to view your newly created `OpenLibertyApplications` resources:

[role='command']
```
kubectl get OpenLibertyApplications
```

You can also replace `OpenLibertyApplications` with the shortname `olapps`.

Look for output that is similar to the following example:

[role='no_copy']
```
NAME      IMAGE                  EXPOSED   RECONCILED   AGE
system    system:1.0-SNAPSHOT    true      True         10s
```

A `RECONCILED` state value of `True` indicates that the operator was able to successfully process the `OpenLibertyApplications` instances. Run the following command to view details of your microservice:

[role='command']
```
kubectl describe olapps/system
```

This example shows part of the `olapps/system` output:

[role='no_copy']
```
Name:         system
Namespace:    default
Labels:       app.kubernetes.io/part-of=system
              name=system
Annotations:  <none>
API Version:  openliberty.io/v1beta1
Kind:         OpenLibertyApplication

...
```

== Accessing the microservice

To access the exposed `system` microservice, the service must be port-forwarded. Run the following command to set up port forwarding to access the `system` service:

[role='command']
```
kubectl port-forward svc/system 9080
```

// Static guide instruction
ifndef::cloud-hosted[]
Visit the microservice at http://localhost:9080/system/properties.
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Open another command-line session by selecting **Terminal** > **New Terminal** from the menu of the IDE. Access the microservice by running the following command:
```
curl -s http://localhost:9080/system/properties | jq
```
{: codeblock}
endif::[]

== Specifying other parameters

You can visit the link:https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide.adoc#configuration[Open Liberty Operator user guide] to find all of the supported optional parameters.

//File 0
deploy.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/deploy.yaml[]
----

You can now configure the readiness and liveness probes. The [hotspot=readinessProbe file=0]`readiness probe` is used to know when a container is ready to begin accepting traffic, and the [hotspot=livenessProbe file=0]`liveness probe` is used to know when to restart a container.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `deploy.yaml` configuration file.#
`deploy.yaml`
----

The health check endpoints `/health/ready` and `/health/live` have already been created for you. 

// Static guide instruction
ifndef::cloud-hosted[]
Run the following command to deploy the `system` microservice with the new configuration:

[role='command']
```
kubectl apply -f deploy.yaml
```
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Run the following commands to update the **applicationImage** and deploy the **system** microservice with the new configuration:
```
sed -i 's=system:1.0-SNAPSHOT=us.icr.io/'"$NAMESPACE_NAME"'/system:1.0-SNAPSHOT\n  imagePullPolicy: Always=g' deploy.yaml
kubectl apply -f deploy.yaml
```
{: codeblock}
endif::[]

// Static guide instruction
ifndef::cloud-hosted[]
Visit the microservice at http://localhost:9080/system/properties.
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Access the microservice by running the following command:
```
curl -s http://localhost:9080/system/properties | jq
```
{: codeblock}
endif::[]

When you're done trying out the microservice, press **CTRL+C** in the command line session where you ran the `kubectl port-forward` command to stop the port forwarding.

== Tearing down the environment

// Static guide instruction
ifndef::cloud-hosted[]
When you no longer need your deployed microservice, you can delete all resources by running the following command:

[role='command']
```
kubectl delete -f deploy.yaml
```

To uninstall the Open Liberty Operator, run the following commands:
[role='command']
```
OPERATOR_NAMESPACE=default
WATCH_NAMESPACE='""'
curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.1/openliberty-app-operator.yaml \
  | sed -e "s/OPEN_LIBERTY_WATCH_NAMESPACE/${WATCH_NAMESPACE}/" \
  | kubectl delete -n ${OPERATOR_NAMESPACE} -f -
curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.1/openliberty-app-cluster-rbac.yaml \
  | sed -e "s/OPEN_LIBERTY_OPERATOR_NAMESPACE/${OPERATOR_NAMESPACE}/" \
  | kubectl delete -f -
kubectl delete -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.1/openliberty-app-crd.yaml
```
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
When you no longer need your deployed microservice, you can delete all resources by running the following command:

```
kubectl delete -f deploy.yaml
```
{: codeblock}
endif::[]

== Great work! You're done!

You just deployed a microservice running in Open Liberty to Kubernetes by using the Open Liberty Operator.

== Related Links

include::{common-includes}/attribution.adoc[subs="attributes"]
