# tag::system[]
apiVersion: openliberty.io/v1beta1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: system
  labels:
    name: system
spec:
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%
  # tag::sysImage[]
  applicationImage: system:1.0-SNAPSHOT
  # end::sysImage[]
  service:
    # tag::servicePort[]
    port: 9080
    # end::servicePort[]
  # end::service[]
  # tag::expose[]
  expose: true
  # end::expose[]
  # tag::systemEnv[]
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  # end::systemEnv[]
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 2
    timeoutSeconds: 10
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 2
    timeoutSeconds: 10
# end::system[]