# tag::system[]
apiVersion: apps.openliberty.io/v1beta2
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: system
  labels:
    name: system
spec:
  # tag::sysImage[]
  applicationImage: system:1.0-SNAPSHOT
  # end::sysImage[]
  # tag::service[]
  service:
    # tag::servicePort[]
    port: 9080
    # end::servicePort[]
  # end::service[]
  # tag::expose[]
  expose: true
  # end::expose[]
  # tag::systemEnv[]
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  # end::systemEnv[]
  # tag::healthProbes[]
  # tag::readinessProbe[]
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 2
    timeoutSeconds: 10
  # end::readinessProbe[]
  # tag::livenessProbe[]
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 2
    timeoutSeconds: 10
  # end::livenessProbe[]
  # tag::healthProbes[]
# end::system[]
