apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  replicas: 2
  strategy:
  type: RollingUpdate
  rollingUpdate:
     maxUnavailable: 25%
     maxSurge: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: system:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        startupProbe:
          httpGet:
            path: /health/started
            port: 9080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
# tag::system[]
apiVersion: openliberty.io/v1beta1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: system
  labels:
    name: system
spec:
  # tag::sysImage[]
  applicationImage: guide/system-imagestream:1.0-SNAPSHOT
  # end::sysImage[]
  service:
    # tag::servicePort[]
    port: 9080
    # end::servicePort[]
  # end::service[]
  # tag::expose[]
  expose: true
  # end::expose[]
  # tag::systemEnv[]
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  # end::systemEnv[]
# end::system[]